---
FactoryBot:
  Enabled: true
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"
    - "**/test/**/*"
    - "**/features/support/factories/**/*.rb"
  DocumentationBaseURL: https://docs.rubocop.org/rubocop-factory_bot

FactoryBot/AttributeDefinedStatically:
  Description: Always declare attribute values as blocks.
  Enabled: true
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb
  VersionAdded: '1.28'
  VersionChanged: '2.0'
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/AttributeDefinedStatically

FactoryBot/ConsistentParenthesesStyle:
  Description: Use a consistent style for parentheses in factory_bot calls.
  Enabled: pending
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - omit_parentheses
  VersionAdded: '2.14'
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/ConsistentParenthesesStyle

FactoryBot/CreateList:
  Description: Checks for create_list usage.
  Enabled: true
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb
  EnforcedStyle: create_list
  SupportedStyles:
    - create_list
    - n_times
  SafeAutoCorrect: false
  VersionAdded: '1.25'
  VersionChanged: "<<next>>"
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/CreateList

FactoryBot/FactoryAssociationWithStrategy:
  Description: Use definition in factory association instead of hard coding a strategy.
  Enabled: pending
  VersionAdded: "<<next>>"
  VersionChanged: '2.23'
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/FactoryAssociationWithStrategy

FactoryBot/FactoryClassName:
  Description: Use string value when setting the class attribute explicitly.
  Enabled: true
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb
  VersionAdded: '1.37'
  VersionChanged: '2.0'
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/FactoryClassName

FactoryBot/FactoryNameStyle:
  Description: Checks for name style for argument of FactoryBot::Syntax::Methods.
  Enabled: pending
  VersionAdded: '2.16'
  EnforcedStyle: symbol
  SupportedStyles:
    - symbol
    - string
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/FactoryNameStyle

FactoryBot/RedundantFactoryOption:
  Description: Checks for redundant `factory` option.
  Enabled: pending
  VersionAdded: "<<next>>"
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/RedundantFactoryOption

FactoryBot/SyntaxMethods:
  Description: Use shorthands from `FactoryBot::Syntax::Methods` in your specs.
  Enabled: pending
  SafeAutoCorrect: false
  VersionAdded: '2.7'
  Reference: https://www.rubydoc.info/gems/rubocop-factory_bot/RuboCop/Cop/FactoryBot/SyntaxMethods
